services:

  api:
    build: .
    volumes:
      - ./scripts:/scripts

  postgres:
    container_name: isy-pg
    image: postgres
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: isy-one
      PGDATA: /data/postgres
  cache:
    container_name: isy-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
